apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deploy
  labels:
    app: app-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-flask
  template:
    metadata:
      labels:
        app: app-flask
    spec:
      containers:
      - name: flask-app
        image: 
        ports:
        - containerPort: 5000
