name: Deploy to EKS


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Initialize Terraform
      run: |
        
        echo "Cloning Repository"
        git clone -b aws-eks-terraform --single-branch https://github.com/Muhammedashraf10/pwc-demo.git
        cd terraform/aws-eks
        terraform init

    - name: Plan Terraform
      run: |
        echo Planning Terraform
        terraform plan
        
    - name: Applying terraform
      run: |
        echo "Applying Terraform
        terraform apply

